env: "local"
database:
  username: postgres
  password: password
  host: localhost
  port: 5432
  dbname: student_manager_db
  sslmode: disable
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
  user: "user"
  password: "password"